spring:
  application:
    name: demo

# Swagger
springdoc:
  swagger-ui:
    tags-sorter: alpha # @Tag 알파벳 오름차순 정렬
    operations-sorter: alpha # @Operation 알파벳 오름차순 정렬
    doc-expansion: none # 페이지 최초 접근 시 최상위 항목만 표시
